server:
  port: 8082

ms-productos:
  url: "http://ms-product:8081"

spring:

  application:
    name: ms-orders

  r2dbc:
    url: r2dbc:postgresql://db-orders:5432/orders_db?currentSchema=public
    username: postgres
    password: admin

  sql:
    init:
      mode: always
      platform: postgres
